import { Outfit } from "next/font/google";
import Providers from "./providers";
import ThemeSwitcher from "./components/ThemeSwitcher";
import Analytics from "@vercel/analytics"

// Components
import NavBar from "./components/base/navbar";
import Footer from "./components/base/footer";

import "./globals.css";

export const metadata = {
  title: { default: "Artentii • Web Developer & Graphic Designer", template: "%s - Artentii" },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image"
  }
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={outfit.className}>
      <body className="bg-light dark:bg-dark text-gray dark:text-white">
        <Providers>
          <div className="noise"></div>
          <NavBar />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
      <Analytics/>
    </html>
  );
}
